### ISSUE TITLE
Error with reviewers of type Group

### ISSUE THREAD

**Issue by SebastienChrist** [shayki5/azure-devops-create-pr-task#50]
Hi,

As we discuss together, I tried to use a group not a team for reviewers but it does not work. I just want to notify the developers of the team (not all the team). 

Regards,

**Comment by shayki5** [comment]
Hi @SebastienChrist,
I fixed it :)
Could you try now and check if it works?

Kind regards,
Shayki

**Comment by SebastienChrist** [comment]
Hi Shayki,

I have an error.
See the log below :

2020-06-22T12:07:53.9703034Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2020-06-22T12:07:53.9705293Z ##[debug]Evaluating: succeeded()
2020-06-22T12:07:53.9705811Z ##[debug]Evaluating succeeded:
2020-06-22T12:07:53.9706870Z ##[debug]=> True
2020-06-22T12:07:53.9707463Z ##[debug]Result: True
2020-06-22T12:07:53.9708068Z ##[section]Starting: Create Pull Request
2020-06-22T12:07:53.9845595Z ==============================================================================
2020-06-22T12:07:53.9845927Z Task         : Create Pull Request
2020-06-22T12:07:53.9846359Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-06-22T12:07:53.9846742Z Version      : 1.2.144
2020-06-22T12:07:53.9846953Z Author       : Shayki Abramczyk
2020-06-22T12:07:53.9847327Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-06-22T12:07:53.9847829Z ==============================================================================
2020-06-22T12:07:54.9864916Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-06-22T12:07:55.1856797Z ##[debug]Entering RunTask.
2020-06-22T12:07:55.2303909Z ##[debug]INPUT_SOURCEBRANCH: 'features/384556_PluginTransaltionManagement'
2020-06-22T12:07:55.2338845Z ##[debug]INPUT_TARGETBRANCH: 'master'
2020-06-22T12:07:55.2443955Z ##[debug]INPUT_TITLE: 'Test'
2020-06-22T12:07:55.2445198Z ##[debug]INPUT_DESCRIPTION (empty)
2020-06-22T12:07:55.2495156Z ##[debug]INPUT_REVIEWERS: 'Shopping_Dev'
2020-06-22T12:07:55.2527911Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-06-22T12:07:55.2601966Z ##[debug]INPUT_ISDRAFT: 'false'
2020-06-22T12:07:55.2608479Z ##[debug] Converted to bool: False
2020-06-22T12:07:55.2640968Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2020-06-22T12:07:55.2664329Z ##[debug] Converted to bool: False
2020-06-22T12:07:55.2696452Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-06-22T12:07:55.2729429Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-06-22T12:07:55.2753219Z ##[debug] Converted to bool: False
2020-06-22T12:07:55.2785914Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-06-22T12:07:55.2818443Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-06-22T12:07:55.2840675Z ##[debug] Converted to bool: False
2020-06-22T12:07:55.2872401Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-06-22T12:07:55.2905610Z ##[debug] Converted to bool: True
2020-06-22T12:07:55.2938971Z ##[debug]INPUT_PROJECTID (empty)
2020-06-22T12:07:55.2971272Z ##[debug]INPUT_GITREPOSITORYID (empty)
2020-06-22T12:07:55.3003690Z ##[debug]INPUT_GITHUBREPOSITORY: 'Y2_Plugins_Clienteling'
2020-06-22T12:07:55.3035872Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2020-06-22T12:07:55.3059291Z ##[debug] Converted to bool: False
2020-06-22T12:07:55.3369288Z The Source Branch is: refs/heads/features/384556_PluginTransaltionManagement
2020-06-22T12:07:55.3377224Z The Target Branch is: refs/heads/master
2020-06-22T12:07:55.3386641Z The Title is: Test
2020-06-22T12:07:55.3395924Z The Description is:
2020-06-22T12:07:55.3404934Z Is Reviewers are: Shopping_Dev
2020-06-22T12:07:55.3452067Z Is Draft Pull Request: False
2020-06-22T12:07:55.5281197Z ##[debug]GET https://dev.azure.com/cegid/Retail/_apis/git/repositories/Y2_Plugins_Clienteling/diffs/commits?baseVersion=features/384556_PluginTransaltionManagement&targetVersion=master&api-version=4.1&$top=2 with 0-byte payload
2020-06-22T12:07:55.6765280Z ##[debug]received 15933-byte response of content type text/html; charset=utf-8
2020-06-22T12:07:55.7268659Z  new commits! perofrm a Pull Request...
2020-06-22T12:07:55.7513620Z ##[debug]GET https://vsaex.dev.azure.com/cegid/_apis/userentitlements?top=5000&api-version=4.1-preview.1 with 0-byte payload
2020-06-22T12:07:56.0113896Z ##[debug]received 15623-byte response of content type text/html; charset=utf-8
2020-06-22T12:07:56.0140464Z ##[debug]GET https://dev.azure.com/cegid/_apis/projects/Retail/teams?api-version=4.1-preview.1 with 0-byte payload
2020-06-22T12:07:56.0739930Z ##[debug]received 15616-byte response of content type text/html; charset=utf-8
2020-06-22T12:07:56.1475623Z ##[debug]Shopping_Dev
2020-06-22T12:07:56.2816430Z ##[debug]GET https://vssps.dev.azure.com/cegid/_apis/graph/groups?api-version=4.1-preview.1 with 0-byte payload
2020-06-22T12:07:56.4542729Z ##[debug]received 15619-byte response of content type text/html; charset=utf-8
2020-06-22T12:07:58.6307727Z ##[debug]Leaving RunTask.
2020-06-22T12:07:58.7148859Z ##[debug]Caught exception from task script.
2020-06-22T12:07:58.7182390Z ##[debug]Error record:
2020-06-22T12:07:58.7834000Z ##[debug]Convertfrom-Json : Invalid JSON primitive: .
2020-06-22T12:07:58.7847859Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.144\createPullRequest.ps1:512 char:52
2020-06-22T12:07:58.7861465Z ##[debug]+ ...               $teamId = ($response.Content | Convertfrom-Json).value. ...
2020-06-22T12:07:58.7875196Z ##[debug]+                                                  ~~~~~~~~~~~~~~~~
2020-06-22T12:07:58.7889439Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
2020-06-22T12:07:58.7904312Z ##[debug]    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
2020-06-22T12:07:58.7920633Z ##[debug]
2020-06-22T12:07:58.7943760Z ##[debug]Script stack trace:
2020-06-22T12:07:58.7982594Z ##[debug]at GetReviewerId, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.144\createPullRequest.ps1: line 512
2020-06-22T12:07:58.7996776Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.144\createPullRequest.ps1: line 292
2020-06-22T12:07:58.8013596Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.144\createPullRequest.ps1: line 120
2020-06-22T12:07:58.8027793Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.144\createPullRequest.ps1: line 54
2020-06-22T12:07:58.8041870Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.144\createPullRequest.ps1: line 628
2020-06-22T12:07:58.8056932Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-22T12:07:58.8071618Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-06-22T12:07:58.8085464Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-06-22T12:07:58.8098994Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-22T12:07:58.8120565Z ##[debug]Exception:
2020-06-22T12:07:58.8171551Z ##[debug]System.ArgumentException: Invalid JSON primitive: .
2020-06-22T12:07:58.8182496Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2020-06-22T12:07:58.8196341Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2020-06-22T12:07:58.8212054Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2020-06-22T12:07:58.8226033Z ##[debug]   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2020-06-22T12:07:58.8239523Z ##[debug]   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2020-06-22T12:07:58.8253128Z ##[debug]   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
2020-06-22T12:07:58.8265692Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2020-06-22T12:07:58.8564742Z ##[error]Invalid JSON primitive: .
2020-06-22T12:07:58.8577230Z ##[debug]Processed: ##vso[task.logissue type=error]Invalid JSON primitive: .
2020-06-22T12:07:58.8587515Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-06-22T12:07:59.1201289Z ##[section]Finishing: Create Pull Request


Regards,

Sébastien Christ
Scrum Master
Customer Support Level 3

+33 (0)4 99 62 32 67


cegid.com<https://www.cegid.com/>


De : Shayki Abramczyk <notifications@github.com>
Envoyé : dimanche 21 juin 2020 15:43
À : shayki5/azure-devops-create-pr-task <azure-devops-create-pr-task@noreply.github.com>
Cc : Sebastien Christ <SCHRIST@cegid.com>; Mention <mention@noreply.github.com>
Objet : Re: [shayki5/azure-devops-create-pr-task] Error with reviewers of type Group (#50)


Hi @SebastienChrist<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSebastienChrist&data=02%7C01%7Cschrist%40cegid.com%7Cab2860c1bb0b4367982408d815e90c7d%7C604e5547f49c44818476c14f22fd79cb%7C0%7C0%7C637283437964238275&sdata=3QUnHd%2F2QiERlBSN%2BwvagepjR9h0zRN%2BY6OBDGW7SdI%3D&reserved=0>,
I fixed it :)
Could you try now and check if it works?

Kind regards,
Shayki

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshayki5%2Fazure-devops-create-pr-task%2Fissues%2F50%23issuecomment-647130256&data=02%7C01%7Cschrist%40cegid.com%7Cab2860c1bb0b4367982408d815e90c7d%7C604e5547f49c44818476c14f22fd79cb%7C0%7C0%7C637283437964238275&sdata=MLHpDG6i5XHzGfISpx7Of6DzZ0iChucXlCRqfd%2FjrB8%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANDDT5BVHHTVB4YQMVBQHB3RXYE7DANCNFSM4OB3YJ6A&data=02%7C01%7Cschrist%40cegid.com%7Cab2860c1bb0b4367982408d815e90c7d%7C604e5547f49c44818476c14f22fd79cb%7C0%7C0%7C637283437964248231&sdata=DSK6bXk%2BRs59XTeYoxwmyDuz1gmgY6mfbV%2BusLF7LJc%3D&reserved=0>.


Cegid est susceptible d’effectuer un traitement sur vos données personnelles à des fins de gestion de notre relation commerciale. Pour plus d’information, consultez https://www.cegid.com/fr/privacy-policy
Ce message et les pièces jointes sont confidentiels et établis à l'attention exclusive de ses destinataires. Toute utilisation ou diffusion, même partielle, non autorisée est interdite. Tout message électronique est susceptible d'altération; Cegid décline donc toute responsabilité au titre de ce message. Si vous n'êtes pas le destinataire de ce message, merci de le détruire et d'avertir l'expéditeur.

Cegid may process your personal data for the purpose of our business relationship management. For more information, please visit our website https://www.cegid.com/en/privacy-policy
This message and any attachments are confidential and intended solely for the addressees. Any unauthorized use or disclosure, either whole or partial is prohibited. E-mails are susceptible to alteration; Cegid shall therefore not be liable for the content of this message. If you are not the intended recipient of this message, please delete it and notify the sender.

**Comment by shayki5** [comment]
It's wired, I success to create the PR with a group as reviewers.
I fixed a small bug, I don't know if it's related, but can you try again now?

**Comment by SebastienChrist** [comment]
I still have an error ☹

I tried with “Shopping_dev” and “[Retail]Shopping_Dev”
When I use “Shopping” (the name of the team) it does not work anymore.
See the attached logs.


[cid:image001.png@01D648AA.B1BA38E0]

[cid:image003.png@01D648AB.5A40EC20]

Regards,

Sébastien Christ
Scrum Master
Customer Support Level 3

+33 (0)4 99 62 32 67


cegid.com<https://www.cegid.com/>


De : Shayki Abramczyk <notifications@github.com>
Envoyé : lundi 22 juin 2020 14:46
À : shayki5/azure-devops-create-pr-task <azure-devops-create-pr-task@noreply.github.com>
Cc : Sebastien Christ <SCHRIST@cegid.com>; Mention <mention@noreply.github.com>
Objet : Re: [shayki5/azure-devops-create-pr-task] Error with reviewers of type Group (#50)


It's wired, I success to create the PR with a group as reviewers.
I fixed a small bug, I don't know if it's related, but can you try again now?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshayki5%2Fazure-devops-create-pr-task%2Fissues%2F50%23issuecomment-647495943&data=02%7C01%7Cschrist%40cegid.com%7C32bc8fbbc23c42419bc908d816aa39cc%7C604e5547f49c44818476c14f22fd79cb%7C0%7C0%7C637284267657704622&sdata=iaHdh00Y8m8lPDjd1npx0pCE9lwTgcWo0bqeK6v3nfw%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANDDT5EDDJJZXMKZNAMZJKLRX5HAXANCNFSM4OB3YJ6A&data=02%7C01%7Cschrist%40cegid.com%7C32bc8fbbc23c42419bc908d816aa39cc%7C604e5547f49c44818476c14f22fd79cb%7C0%7C0%7C637284267657714618&sdata=ub8vKopUcMw55YPaiEBuU1kGomcxnRiCr%2FZxTDhSthc%3D&reserved=0>.


Cegid est susceptible d’effectuer un traitement sur vos données personnelles à des fins de gestion de notre relation commerciale. Pour plus d’information, consultez https://www.cegid.com/fr/privacy-policy
Ce message et les pièces jointes sont confidentiels et établis à l'attention exclusive de ses destinataires. Toute utilisation ou diffusion, même partielle, non autorisée est interdite. Tout message électronique est susceptible d'altération; Cegid décline donc toute responsabilité au titre de ce message. Si vous n'êtes pas le destinataire de ce message, merci de le détruire et d'avertir l'expéditeur.

Cegid may process your personal data for the purpose of our business relationship management. For more information, please visit our website https://www.cegid.com/en/privacy-policy
This message and any attachments are confidential and intended solely for the addressees. Any unauthorized use or disclosure, either whole or partial is prohibited. E-mails are susceptible to alteration; Cegid shall therefore not be liable for the content of this message. If you are not the intended recipient of this message, please delete it and notify the sender.

2020-06-22T13:36:31.2967161Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2020-06-22T13:36:31.2969959Z ##[debug]Evaluating: succeeded()
2020-06-22T13:36:31.2970483Z ##[debug]Evaluating succeeded:
2020-06-22T13:36:31.2971685Z ##[debug]=> True
2020-06-22T13:36:31.2972224Z ##[debug]Result: True
2020-06-22T13:36:31.2972808Z ##[section]Starting: Create Pull Request
2020-06-22T13:36:31.3127586Z ==============================================================================
2020-06-22T13:36:31.3127977Z Task         : Create Pull Request
2020-06-22T13:36:31.3128388Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-06-22T13:36:31.3128769Z Version      : 1.2.145
2020-06-22T13:36:31.3129030Z Author       : Shayki Abramczyk
2020-06-22T13:36:31.3129394Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-06-22T13:36:31.3129811Z ==============================================================================
2020-06-22T13:36:35.0990740Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-06-22T13:36:35.3076444Z ##[debug]Entering RunTask.
2020-06-22T13:36:35.5131028Z ##[debug]INPUT_SOURCEBRANCH: 'features/384556_PluginTransaltionManagement'
2020-06-22T13:36:35.5192056Z ##[debug]INPUT_TARGETBRANCH: 'master'
2020-06-22T13:36:35.5235263Z ##[debug]INPUT_TITLE: 'Test'
2020-06-22T13:36:35.5295855Z ##[debug]INPUT_DESCRIPTION (empty)
2020-06-22T13:36:35.5401356Z ##[debug]INPUT_REVIEWERS: 'Shopping'
2020-06-22T13:36:35.5448488Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-06-22T13:36:35.5495055Z ##[debug]INPUT_ISDRAFT: 'false'
2020-06-22T13:36:35.5570215Z ##[debug] Converted to bool: False
2020-06-22T13:36:35.5614347Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2020-06-22T13:36:35.5645387Z ##[debug] Converted to bool: False
2020-06-22T13:36:35.5688720Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-06-22T13:36:35.5735154Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-06-22T13:36:35.5766303Z ##[debug] Converted to bool: False
2020-06-22T13:36:35.5802829Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-06-22T13:36:35.5844467Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-06-22T13:36:35.5876911Z ##[debug] Converted to bool: False
2020-06-22T13:36:35.5925013Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-06-22T13:36:35.5954683Z ##[debug] Converted to bool: True
2020-06-22T13:36:35.5993427Z ##[debug]INPUT_PROJECTID (empty)
2020-06-22T13:36:35.6035244Z ##[debug]INPUT_GITREPOSITORYID (empty)
2020-06-22T13:36:35.6086066Z ##[debug]INPUT_GITHUBREPOSITORY: 'Y2_Plugins_Clienteling'
2020-06-22T13:36:35.6135633Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2020-06-22T13:36:35.6165601Z ##[debug] Converted to bool: False
2020-06-22T13:36:35.6562343Z The Source Branch is: refs/heads/features/384556_PluginTransaltionManagement
2020-06-22T13:36:35.6577769Z The Target Branch is: refs/heads/master
2020-06-22T13:36:35.6594373Z The Title is: Test
2020-06-22T13:36:35.6610150Z The Description is: 
2020-06-22T13:36:35.6627200Z Is Reviewers are: Shopping
2020-06-22T13:36:35.6692711Z Is Draft Pull Request: False
2020-06-22T13:36:35.9542279Z ##[debug]GET https://dev.azure.com/cegid/Retail/_apis/git/repositories/Y2_Plugins_Clienteling/diffs/commits?baseVersion=features/384556_PluginTransaltionManagement&targetVersion=master&api-version=4.1&$top=2 with 0-byte payload
2020-06-22T13:36:36.1978350Z ##[debug]received 15933-byte response of content type text/html; charset=utf-8
2020-06-22T13:36:36.3138234Z  new commits! perofrm a Pull Request...
2020-06-22T13:36:36.3394079Z ##[debug]GET https://vsaex.dev.azure.com/cegid/_apis/userentitlements?top=5000&api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:36:36.5061327Z ##[debug]received 15623-byte response of content type text/html; charset=utf-8
2020-06-22T13:36:36.5106624Z ##[debug]GET https://dev.azure.com/cegid/_apis/projects/Retail/teams?api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:36:36.5428475Z ##[debug]received 15616-byte response of content type text/html; charset=utf-8
2020-06-22T13:36:36.5534206Z ##[debug]Shopping
2020-06-22T13:36:36.6603586Z ##[debug]GET https://vssps.dev.azure.com/cegid/_apis/graph/groups?api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:36:36.7107491Z ##[debug]received 15619-byte response of content type text/html; charset=utf-8
2020-06-22T13:36:37.6187278Z ##[debug]Leaving RunTask.
2020-06-22T13:36:37.6295633Z ##[debug]Caught exception from task script.
2020-06-22T13:36:37.6357349Z ##[debug]Error record:
2020-06-22T13:36:37.7584041Z ##[debug]Convertfrom-Json : Invalid JSON primitive: .
2020-06-22T13:36:37.7611653Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1:512 char:52
2020-06-22T13:36:37.7635917Z ##[debug]+ ...               $teamId = ($response.Content | Convertfrom-Json).value. ...
2020-06-22T13:36:37.7662896Z ##[debug]+                                                  ~~~~~~~~~~~~~~~~
2020-06-22T13:36:37.7686442Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
2020-06-22T13:36:37.7708131Z ##[debug]    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
2020-06-22T13:36:37.7731197Z ##[debug] 
2020-06-22T13:36:37.7772127Z ##[debug]Script stack trace:
2020-06-22T13:36:37.7843813Z ##[debug]at GetReviewerId, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 512
2020-06-22T13:36:37.7866580Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 292
2020-06-22T13:36:37.7890463Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 120
2020-06-22T13:36:37.7915099Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 54
2020-06-22T13:36:37.7939747Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 628
2020-06-22T13:36:37.7963121Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-22T13:36:37.7986454Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-06-22T13:36:37.8008552Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-06-22T13:36:37.8034386Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-22T13:36:37.8066531Z ##[debug]Exception:
2020-06-22T13:36:37.8145493Z ##[debug]System.ArgumentException: Invalid JSON primitive: .
2020-06-22T13:36:37.8169851Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2020-06-22T13:36:37.8195197Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2020-06-22T13:36:37.8221703Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2020-06-22T13:36:37.8243999Z ##[debug]   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2020-06-22T13:36:37.8269414Z ##[debug]   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2020-06-22T13:36:37.8293799Z ##[debug]   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
2020-06-22T13:36:37.8314136Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2020-06-22T13:36:37.8664703Z ##[error]Invalid JSON primitive: .
2020-06-22T13:36:37.8675906Z ##[debug]Processed: ##vso[task.logissue type=error]Invalid JSON primitive: .
2020-06-22T13:36:37.8685046Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-06-22T13:36:37.9672222Z ##[section]Finishing: Create Pull Request
2020-06-22T13:26:09.9028136Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2020-06-22T13:26:09.9030138Z ##[debug]Evaluating: succeeded()
2020-06-22T13:26:09.9030684Z ##[debug]Evaluating succeeded:
2020-06-22T13:26:09.9031742Z ##[debug]=> True
2020-06-22T13:26:09.9032381Z ##[debug]Result: True
2020-06-22T13:26:09.9033004Z ##[section]Starting: Create Pull Request
2020-06-22T13:26:09.9160519Z ==============================================================================
2020-06-22T13:26:09.9160883Z Task         : Create Pull Request
2020-06-22T13:26:09.9161308Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-06-22T13:26:09.9161689Z Version      : 1.2.145
2020-06-22T13:26:09.9161900Z Author       : Shayki Abramczyk
2020-06-22T13:26:09.9162273Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-06-22T13:26:09.9162673Z ==============================================================================
2020-06-22T13:26:10.9207046Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-06-22T13:26:11.1565854Z ##[debug]Entering RunTask.
2020-06-22T13:26:11.2345441Z ##[debug]INPUT_SOURCEBRANCH: 'features/384556_PluginTransaltionManagement'
2020-06-22T13:26:11.2369808Z ##[debug]INPUT_TARGETBRANCH: 'master'
2020-06-22T13:26:11.2470543Z ##[debug]INPUT_TITLE: 'Test'
2020-06-22T13:26:11.2471471Z ##[debug]INPUT_DESCRIPTION (empty)
2020-06-22T13:26:11.2496221Z ##[debug]INPUT_REVIEWERS: 'Shopping_Dev'
2020-06-22T13:26:11.2527786Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-06-22T13:26:11.2596991Z ##[debug]INPUT_ISDRAFT: 'false'
2020-06-22T13:26:11.2600434Z ##[debug] Converted to bool: False
2020-06-22T13:26:11.2630669Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2020-06-22T13:26:11.2653667Z ##[debug] Converted to bool: False
2020-06-22T13:26:11.2683675Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-06-22T13:26:11.2720508Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-06-22T13:26:11.2735776Z ##[debug] Converted to bool: False
2020-06-22T13:26:11.2770812Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-06-22T13:26:11.2799986Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-06-22T13:26:11.2820190Z ##[debug] Converted to bool: False
2020-06-22T13:26:11.2848777Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-06-22T13:26:11.2868581Z ##[debug] Converted to bool: True
2020-06-22T13:26:11.2896667Z ##[debug]INPUT_PROJECTID (empty)
2020-06-22T13:26:11.2925813Z ##[debug]INPUT_GITREPOSITORYID (empty)
2020-06-22T13:26:11.2955181Z ##[debug]INPUT_GITHUBREPOSITORY: 'Y2_Plugins_Clienteling'
2020-06-22T13:26:11.2984321Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2020-06-22T13:26:11.3005238Z ##[debug] Converted to bool: False
2020-06-22T13:26:11.3300031Z The Source Branch is: refs/heads/features/384556_PluginTransaltionManagement
2020-06-22T13:26:11.3308470Z The Target Branch is: refs/heads/master
2020-06-22T13:26:11.3316838Z The Title is: Test
2020-06-22T13:26:11.3325875Z The Description is: 
2020-06-22T13:26:11.3333896Z Is Reviewers are: Shopping_Dev
2020-06-22T13:26:11.3379030Z Is Draft Pull Request: False
2020-06-22T13:26:11.5083594Z ##[debug]GET https://dev.azure.com/cegid/Retail/_apis/git/repositories/Y2_Plugins_Clienteling/diffs/commits?baseVersion=features/384556_PluginTransaltionManagement&targetVersion=master&api-version=4.1&$top=2 with 0-byte payload
2020-06-22T13:26:11.6127023Z ##[debug]received 15933-byte response of content type text/html; charset=utf-8
2020-06-22T13:26:11.6778794Z  new commits! perofrm a Pull Request...
2020-06-22T13:26:11.7058907Z ##[debug]GET https://vsaex.dev.azure.com/cegid/_apis/userentitlements?top=5000&api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:26:11.8839765Z ##[debug]received 15623-byte response of content type text/html; charset=utf-8
2020-06-22T13:26:11.8840488Z ##[debug]GET https://dev.azure.com/cegid/_apis/projects/Retail/teams?api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:26:11.9391908Z ##[debug]received 15616-byte response of content type text/html; charset=utf-8
2020-06-22T13:26:12.0132383Z ##[debug]Shopping_Dev
2020-06-22T13:26:12.1532276Z ##[debug]GET https://vssps.dev.azure.com/cegid/_apis/graph/groups?api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:26:12.2894729Z ##[debug]received 15619-byte response of content type text/html; charset=utf-8
2020-06-22T13:26:15.2343801Z ##[debug]Leaving RunTask.
2020-06-22T13:26:15.3163777Z ##[debug]Caught exception from task script.
2020-06-22T13:26:15.3198634Z ##[debug]Error record:
2020-06-22T13:26:15.3792612Z ##[debug]Convertfrom-Json : Invalid JSON primitive: .
2020-06-22T13:26:15.3804436Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1:512 char:52
2020-06-22T13:26:15.3816699Z ##[debug]+ ...               $teamId = ($response.Content | Convertfrom-Json).value. ...
2020-06-22T13:26:15.3828711Z ##[debug]+                                                  ~~~~~~~~~~~~~~~~
2020-06-22T13:26:15.3841911Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
2020-06-22T13:26:15.3853762Z ##[debug]    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
2020-06-22T13:26:15.3865641Z ##[debug] 
2020-06-22T13:26:15.3886247Z ##[debug]Script stack trace:
2020-06-22T13:26:15.3921953Z ##[debug]at GetReviewerId, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 512
2020-06-22T13:26:15.3934551Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 292
2020-06-22T13:26:15.3947159Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 120
2020-06-22T13:26:15.3959270Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 54
2020-06-22T13:26:15.3971918Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 628
2020-06-22T13:26:15.3983978Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-22T13:26:15.3996787Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-06-22T13:26:15.4009757Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-06-22T13:26:15.4021921Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-22T13:26:15.4041607Z ##[debug]Exception:
2020-06-22T13:26:15.4090730Z ##[debug]System.ArgumentException: Invalid JSON primitive: .
2020-06-22T13:26:15.4103936Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2020-06-22T13:26:15.4116335Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2020-06-22T13:26:15.4128573Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2020-06-22T13:26:15.4140818Z ##[debug]   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2020-06-22T13:26:15.4302430Z ##[debug]   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2020-06-22T13:26:15.4317090Z ##[debug]   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
2020-06-22T13:26:15.4329628Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2020-06-22T13:26:15.4603279Z ##[error]Invalid JSON primitive: .
2020-06-22T13:26:15.4616223Z ##[debug]Processed: ##vso[task.logissue type=error]Invalid JSON primitive: .
2020-06-22T13:26:15.4636992Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-06-22T13:26:15.8116417Z ##[section]Finishing: Create Pull Request
2020-06-22T13:30:49.0833999Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2020-06-22T13:30:49.0835874Z ##[debug]Evaluating: succeeded()
2020-06-22T13:30:49.0836452Z ##[debug]Evaluating succeeded:
2020-06-22T13:30:49.0837601Z ##[debug]=> True
2020-06-22T13:30:49.0838126Z ##[debug]Result: True
2020-06-22T13:30:49.0838649Z ##[section]Starting: Create Pull Request
2020-06-22T13:30:49.0955264Z ==============================================================================
2020-06-22T13:30:49.0955574Z Task         : Create Pull Request
2020-06-22T13:30:49.0955988Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-06-22T13:30:49.0956371Z Version      : 1.2.145
2020-06-22T13:30:49.0956579Z Author       : Shayki Abramczyk
2020-06-22T13:30:49.0956946Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-06-22T13:30:49.0957338Z ==============================================================================
2020-06-22T13:30:50.0210467Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-06-22T13:30:50.1922743Z ##[debug]Entering RunTask.
2020-06-22T13:30:50.2343506Z ##[debug]INPUT_SOURCEBRANCH: 'features/384556_PluginTransaltionManagement'
2020-06-22T13:30:50.2374242Z ##[debug]INPUT_TARGETBRANCH: 'master'
2020-06-22T13:30:50.2481730Z ##[debug]INPUT_TITLE: 'Test'
2020-06-22T13:30:50.2482855Z ##[debug]INPUT_DESCRIPTION (empty)
2020-06-22T13:30:50.2523780Z ##[debug]INPUT_REVIEWERS: '[Retail]\Shopping_Dev'
2020-06-22T13:30:50.2654245Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-06-22T13:30:50.2688070Z ##[debug]INPUT_ISDRAFT: 'false'
2020-06-22T13:30:50.2689109Z ##[debug] Converted to bool: False
2020-06-22T13:30:50.2695888Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2020-06-22T13:30:50.2747694Z ##[debug] Converted to bool: False
2020-06-22T13:30:50.2770556Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-06-22T13:30:50.2830966Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-06-22T13:30:50.2855369Z ##[debug] Converted to bool: False
2020-06-22T13:30:50.2913088Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-06-22T13:30:50.2916359Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-06-22T13:30:50.2929075Z ##[debug] Converted to bool: False
2020-06-22T13:30:50.2956927Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-06-22T13:30:50.2978495Z ##[debug] Converted to bool: True
2020-06-22T13:30:50.3009737Z ##[debug]INPUT_PROJECTID (empty)
2020-06-22T13:30:50.3036483Z ##[debug]INPUT_GITREPOSITORYID (empty)
2020-06-22T13:30:50.3065491Z ##[debug]INPUT_GITHUBREPOSITORY: 'Y2_Plugins_Clienteling'
2020-06-22T13:30:50.3095289Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2020-06-22T13:30:50.3120173Z ##[debug] Converted to bool: False
2020-06-22T13:30:50.3412086Z The Source Branch is: refs/heads/features/384556_PluginTransaltionManagement
2020-06-22T13:30:50.3420254Z The Target Branch is: refs/heads/master
2020-06-22T13:30:50.3428898Z The Title is: Test
2020-06-22T13:30:50.3437243Z The Description is: 
2020-06-22T13:30:50.3446111Z Is Reviewers are: [Retail]\Shopping_Dev
2020-06-22T13:30:50.3490193Z Is Draft Pull Request: False
2020-06-22T13:30:50.4816189Z ##[debug]GET https://dev.azure.com/cegid/Retail/_apis/git/repositories/Y2_Plugins_Clienteling/diffs/commits?baseVersion=features/384556_PluginTransaltionManagement&targetVersion=master&api-version=4.1&$top=2 with 0-byte payload
2020-06-22T13:30:50.6217586Z ##[debug]received 15933-byte response of content type text/html; charset=utf-8
2020-06-22T13:30:50.6729162Z  new commits! perofrm a Pull Request...
2020-06-22T13:30:50.6946046Z ##[debug]GET https://vsaex.dev.azure.com/cegid/_apis/userentitlements?top=5000&api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:30:50.8429906Z ##[debug]received 15623-byte response of content type text/html; charset=utf-8
2020-06-22T13:30:50.8458971Z ##[debug]GET https://dev.azure.com/cegid/_apis/projects/Retail/teams?api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:30:50.8752527Z ##[debug]received 15616-byte response of content type text/html; charset=utf-8
2020-06-22T13:30:50.8870044Z ##[debug][Retail]\Shopping_Dev
2020-06-22T13:30:51.0146770Z ##[debug]GET https://vssps.dev.azure.com/cegid/_apis/graph/groups?api-version=4.1-preview.1 with 0-byte payload
2020-06-22T13:30:51.0675424Z ##[debug]received 15619-byte response of content type text/html; charset=utf-8
2020-06-22T13:30:52.9411265Z ##[debug]Leaving RunTask.
2020-06-22T13:30:52.9770377Z ##[debug]Caught exception from task script.
2020-06-22T13:30:52.9804561Z ##[debug]Error record:
2020-06-22T13:30:53.0523748Z ##[debug]Convertfrom-Json : Invalid JSON primitive: .
2020-06-22T13:30:53.0535861Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1:512 char:52
2020-06-22T13:30:53.0548008Z ##[debug]+ ...               $teamId = ($response.Content | Convertfrom-Json).value. ...
2020-06-22T13:30:53.0559693Z ##[debug]+                                                  ~~~~~~~~~~~~~~~~
2020-06-22T13:30:53.0573017Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
2020-06-22T13:30:53.0584772Z ##[debug]    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
2020-06-22T13:30:53.0596776Z ##[debug] 
2020-06-22T13:30:53.0615373Z ##[debug]Script stack trace:
2020-06-22T13:30:53.0650199Z ##[debug]at GetReviewerId, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 512
2020-06-22T13:30:53.0664879Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 292
2020-06-22T13:30:53.0681437Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 120
2020-06-22T13:30:53.0696351Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 54
2020-06-22T13:30:53.0708436Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.145\createPullRequest.ps1: line 628
2020-06-22T13:30:53.0719834Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-22T13:30:53.0730893Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-06-22T13:30:53.0743065Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-06-22T13:30:53.0755005Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-22T13:30:53.0774563Z ##[debug]Exception:
2020-06-22T13:30:53.0826678Z ##[debug]System.ArgumentException: Invalid JSON primitive: .
2020-06-22T13:30:53.0838602Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
2020-06-22T13:30:53.0854119Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
2020-06-22T13:30:53.0866711Z ##[debug]   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
2020-06-22T13:30:53.0878990Z ##[debug]   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
2020-06-22T13:30:53.0892082Z ##[debug]   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
2020-06-22T13:30:53.0905124Z ##[debug]   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
2020-06-22T13:30:53.0916174Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2020-06-22T13:30:53.1182683Z ##[error]Invalid JSON primitive: .
2020-06-22T13:30:53.1194587Z ##[debug]Processed: ##vso[task.logissue type=error]Invalid JSON primitive: .
2020-06-22T13:30:53.1203634Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-06-22T13:30:53.3889373Z ##[section]Finishing: Create Pull Request

**Comment by SebastienChrist** [comment]
Ok the last fix works fine. I can use Groups for pull request notifications now! 
Thanks a lot.
